### ISSUE TITLE
not find in index file

### ISSUE THREAD

**Issue by birjubhatt** [AshikNesin/remove-pdf-password#2]
i am new in react native and i install this library but after install build was failed because this library was not find in index file ..i attached screenshot  ...what is process for this ?
![croped-1](https://user-images.githubusercontent.com/21102131/152728592-f56e15d8-1c24-437a-975b-666836ef00f7.png)
![croped-3](https://user-images.githubusercontent.com/21102131/152729480-c6f6aab3-8286-45b1-a682-5448d3e0fadb.png)

**Comment by AshikNesin** [comment]
Hi @birjubhatt,

I don't think this package will work on React Native since it has dependency on [qpdf](https://github.com/AshikNesin/remove-pdf-password#dependency)
